//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektMVC.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Przepi
    {
        public int IdPrzepis { get; set; }
        [Required]
        [MaxLength(100)]
        public string Skladniki { get; set; }
        [Required]
        [MaxLength(200)]
        public string Opis { get; set; }
    }
}
